import 'package:flutter/material.dart';

const infoSheetContent = [
  Text(
      'Spotkin updates one of your Spotify playlists every day with a random selection of tracks from any of your playlists.'),
  SizedBox(height: 10),
  Text(
      'Spotkin was developed to eliminate the need for fiddling with the Spotify app, offering a great selection of music in one playlist every day.'),
  SizedBox(height: 10),
  Text(
      'It will run automatically .... or by clicking the "Update Spotkin On Spotify" button.'),
  SizedBox(height: 10),
  Text(
      'Spotkin works best when drawing from a variety of playlists, including:'),
  Text('• Dynamic playlists like "New Music Friday" or "Today\'s Top Hits"'),
  Text('• Large curated playlists like Rolling Stone\'s "fivehundredalbums"'),
  Text(
      '• Playlists generated by the new_albums script, featuring the latest releases in your preferred genres'),
  SizedBox(height: 10),
  Text(
      'You can create a recipe for each playlist, specifying other playlists to source music from.'),
  SizedBox(height: 10),
  Text(
      'Spotkin allows you to ban artists, tracks, or genres, helping you avoid music you don\'t like or want to hear at the moment.'),
  SizedBox(height: 10),
  Text(
      'You can also specify artists, tracks, genres, and energy levels to include or exclude from your target playlist.'),
  SizedBox(height: 10),
  Text(
      'Spotkin processes your recipes and updates your playlists with new music when you click the "Update Spotkin On Spotify" button.'),
  SizedBox(height: 10),
  Text(
      'This tool helps keep your listening fresh and exciting by automatically updating them with new music tailored to your preferences.'),
];
